name: HTML Validate

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install html-validate
        run: npm install -g html-validate

      - name: Run html-validate
        run: |
          # Busca recursivamente .html en el repo y valida
          find . -type f -name "*.html" -print0 | xargs -0 -n1 html-validate || true
          # Fallos harán que el job termine con error; si quieres que reporte pero no falle, captura el exit code.

